package life.qbic.database;

/**
 * Created by sven on 12/11/16.
 */
public enum QuerryType {

    PROJECTSTATUS_OPEN,
    PROJECTSTATUS_INPROGRESS,
    PROJECTSTATUS_CLOSED,
    GET_FOLLOWING_PROJECTS,
    FOLLOW_PROJECT,
    UNFOLLOW_PROJECT,
    CHECK_PROJECT_PRESENCE,
    PROJECT_REGISTERED_RAWDATA


}
